export const environment = {
    SERVER_URL: `./`,
    FE_URL: 'http://localhost:4200',
    BASE_API_URL: 'https://localhost:9001/',
    APP_RATE_ID: '69006981708944de8259baeba4b1a602',
    BASE_UPLOAD_URL: 'https://localhost:9001/api/v1/upload',
    BASE_FILE_URL: 'https://localhost:9001/Images/',
    ClientPayPalId: 'AfprWRRqkGWWLp-rI7rqducrD0aZ0Cy6Y_WnHTTI824vpjnrtijcGUM4qSRidTVZZdIIHg6uhI8coHur',
    API_RATE_MONEY_KEY: '3479f9b5af3d82af0e54',
    API_RATE_MONEY: 'https://openexchangerates.org/',
    ALLOW_ANONYMOUS: '?_allow_anonymous=true',
    production: false,
    useHash: false,
    hmr: false,
    pro: {
        theme: 'light',
        menu: 'side',
        contentWidth: 'fluid',
        fixedHeader: true,
        autoHideHeader: true,
        fixSiderbar: true,
        onlyIcon: false,
        colorWeak: false,
    },
};